name: retarus_sdk_python_sms_pipeline

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  testing:
    runs-on: ubuntu-22.04
    env:
      retarus_userid: ${{ secrets.RETARUS_USERID }}
      retarus_sms_password: ${{ secrets.RETARUS_SMS_PASSWORD }}
    strategy:
      matrix:
        python-version: ["3.8", "3.10"]


    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: install packages
        run: |
          pip install .

      - name: Test with pytest
        run: |
          pytest tests/test.py

  building:
    needs: testing
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v1
      - name: install requirements
        run: pip install -r requirements.txt

      - name: build package
        run: |
         pip install build 
         python3 -m build --sdist --wheel --outdir dist/ .

      - uses: actions/upload-artifact@v2
        with:
          path: dist
          name: ci_python_sms
  deploy:
    if: github.ref == 'refs/heads/master'
    env:
      pypi: ${{ secrets.PIPY_API_TOKEN}}
      pypi_user: ${{ secrets.PIPY_API_USER}}
    needs: building
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install twine
        run: pip install twine
      - run: mkdir -p  ~/download-art
      - uses: actions/download-artifact@v2
        with:
          key: ci_python_sms
          name: ci_python_sms
          path: ~/download-art
      
      - name: upload artifacts
        run: |
          python3 -m twine upload -u $pypi_user -p $pypi ~/download-art/* --non-interactive --verbose