name: retarus_sdk_python_sms_pipeline

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  testing:
    runs-on: ubuntu-22.04
    env:
      retarus_userid: ${{ secrets.RETARUS_USERID }}
      retarus_fax_password: ${{ secrets.RETARUS_FAX_PASSWORD }}
      retarus_sms_password: ${{ secrets.RETARUS_SMS_PASSWORD }}
      retarus_customer_number: ${{ secrets.CUSTOMER_NUMBER }}
    strategy:
      matrix:
        python-version: ["3.8", "3.10"]


    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: install packages
        run: |
          pip install .

      - name: Test with pytest
        run: |
          pytest tests/test.py

  building:
    needs: testing
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v1
      - name: install requirements
        run: pip install -r requirements.txt

      - name: build package
        run: |
         pip install build 
         python3 -m build --sdist --wheel --outdir dist/ .

      - uses: actions/cache@v3
        with:
          path: dist
          key: gh_action_retarus_sdk_python

  deploy:
    needs: building
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/cache@v3
        with:
          path: dist
          key: gh_action_retarus_sdk_python
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PIPY_API_TOKEN }}
